### ISSUE TITLE
Plugin zip file folder structure

### ISSUE THREAD

**Issue by Ezyweb-uk** [TukuToi/tukutoi-plugin-generator#13]
Tested online at https://www.generateplugins.com/#generate-plugin

Would it be better to generate the zip file with all files and folders within a top folder named using the plugin name, so that the folder structure matches that for a WP plugin ready for upload? There was no top folder in the zip downloaded from the online generator.

Also tested locally on XAMPP, the form loaded ok but it froze after completing and then clicking the Generate button, maybe due to my local web server config.

**Comment by TukuToi** [comment]
It's been a while already I created that, I think there were one or two pending "issues", which you now might experience.
Let me check this asap and get back at you (I am quite sure to remember that it also did not full replace all strings inside the plugin properly with the new data submitted in the form, and the online version of the plugin _definitly_ is not the same as on Github anymore, so I have to sync these versions and iron out the quirks)

Thanks for the heads up. Will be updating asap.

**Comment by Ezyweb-uk** [comment]
Nice project! Just noticed the online generator didn't replace 'plugin_name' in the uninstall.php file, you probably already know as you explain above (looks like uninstall function has moved from a class to top level for reasons explained in the file comments).

**Comment by TukuToi** [comment]
@Ezyweb-uk 

1. I downloaded a generated plugin from https://www.generateplugins.com/#generate-plugin and I received a ready to go Plugin ZIP named `my-plugin-name.zip`. Unzipping it is a folder with same name, inside which all plugin files are located. So this seems to work fine for me.
2. Indeed the process does not replace prefixes such as `plugin_name_uninstall` to `my_plugin_name_uninstall`, throughout the entire plugin.
3. It also does not replace `plugin_name` standalone vars such as `$plugin_name` with the proper new name. However _this_ is expected - these vars are localised in the Classes and get populated with the actual plugin name, so that is fine.
3. It also does not replace the `Requires at least: 1.0.0` and `Tested up to: 5.8` parts in the main file or readme.
4. I noticed some warnings logged when activating in bulk, and that needs a fix too

Note, all these tests where made with the online version - not with the code in this GIT which is not the 1:1 same version.
I have to fix, sync and then re-upload to the respective instances.

Before I start, can you describe what you do/did to get a download without top folder? How does it even download the items if not zipped in a single top folder? Are you getting multiple downloads instead?

Thanks!

**Comment by TukuToi** [comment]
All Issues I had found should now be resolved in https://github.com/TukuToi/tukutoi-plugin-generator/commit/729ce74d21063912b1753b6889143508b116289f
I will test this tomorrow again and then release + update online instance.

**Comment by smileBeda** [comment]
@Ezyweb-uk I have put a new release #20 out, tested and should all be resolved now.
Note that the source also changed (https://github.com/TukuToi/better-wp-plugin-boilerplate/releases/tag/4.0.0)

There is one issue that is not related to the plugin, but the server. The /builds needs to be writable, otherwise the plugin cannot generate the downloadable goods.
I think this is only an issue in hardly locked down servers (like my own), and I am no expert in this, so I will chat about the issue with someone I know that might help me make this safe, then I will update the readme to illustrate this edge case.

If you still have an issue using the online instance or local, please let me know.

Thanks!
